import { createHash } from 'node:crypto';
import { gunzipSync } from 'node:zlib';
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { dirname, join, posix } from 'node:path';

const VENDOR = join(import.meta.dirname, '..', 'vendor');

const PACKAGES = [
  {
    name: 'three', version: '0.186.1', importMap: { 'three': 'build/three.module.js', 'three/addons/': 'examples/jsm/', 'three/examples/jsm/': 'examples/jsm/' },
    entries: [
      'build/three.module.js',
      'examples/jsm/loaders/GLTFLoader.js',
      'examples/jsm/loaders/DRACOLoader.js',
      'examples/jsm/loaders/KTX2Loader.js',
      'examples/jsm/libs/meshopt_decoder.module.js',
      'examples/jsm/objects/Sky.js',
      'examples/jsm/lights/SunLight.js',
      'examples/jsm/postprocessing/Pass.js'
    ],
    dirs: ['examples/jsm/libs/draco/gltf/', 'examples/jsm/libs/basis/'],
    files: ['LICENSE']
  },
  { name: 'three-mesh-bvh', version: '0.9.15', importMap: { 'three-mesh-bvh': 'build/index.module.js' }, entries: ['build/index.module.js'], dirs: [], files: ['LICENSE'] },
  { name: 'postprocessing', version: '6.39.5', importMap: { 'postprocessing': 'build/index.js' }, entries: ['build/index.js'], dirs: [], files: ['LICENSE.md'] },
  { name: 'n8ao', version: '2.0.1', importMap: { 'n8ao': 'dist/N8AO.js' }, entries: ['dist/N8AO.js'], dirs: [], files: ['LICENSE'] },
  { name: 'peerjs', version: '1.5.5', importMap: { 'peerjs': 'dist/peerjs.min.js' }, entries: ['dist/peerjs.min.js'], dirs: [], files: ['LICENSE'] },
  { name: 'acorn', version: '8.18.0', importMap: {}, entries: ['dist/acorn.mjs'], dirs: [], files: ['LICENSE'] }
];

function untar(buf) {
  const out = new Map();
  let off = 0, longName = null;
  while (off + 512 <= buf.length) {
    const h = buf.subarray(off, off + 512);
    if (h.every(b => b === 0)) break;
    const str = (a, b) => h.subarray(a, b).toString('utf8').replace(/\0.*$/s, '');
    const size = parseInt(str(124, 136).trim() || '0', 8);
    const type = String.fromCharCode(h[156] || 48);
    const body = buf.subarray(off + 512, off + 512 + size);
    let name = longName || (str(345, 500) ? str(345, 500) + '/' : '') + str(0, 100);
    longName = null;
    if (type === 'L') longName = body.toString('utf8').replace(/\0.*$/s, '');
    else if (type === 'x') { const m = /\d+ path=([^\n]+)\n/.exec(body.toString('utf8')); if (m) longName = m[1]; }
    else if (type === '0' || type === '\0') out.set(name.replace(/^[^/]+\//, ''), Buffer.from(body));
    off += 512 + Math.ceil(size / 512) * 512;
  }
  return out;
}

function closure(files, entries) {
  const keep = new Set();
  const stack = [...entries];
  while (stack.length) {
    const f = stack.pop();
    if (keep.has(f)) continue;
    if (!files.has(f)) throw new Error(`missing file ${f}`);
    keep.add(f);
    if (!f.endsWith('.js') && !f.endsWith('.mjs')) continue;
    const src = files.get(f).toString('utf8');
    const re = /^\s*(?:import|export)\b[^;'"]*?(?:from\s*)?['"](\.{1,2}\/[^'"]+)['"]|\bimport\(\s*['"](\.{1,2}\/[^'"]+)['"]\s*\)/gm;
    for (let m; (m = re.exec(src));) stack.push(posix.normalize(posix.join(posix.dirname(f), m[1] || m[2])));
    const map = /\/\/# sourceMappingURL=([^\s]+)\s*$/.exec(src);
    if (map) { const p = posix.join(posix.dirname(f), map[1]); if (files.has(p)) keep.add(p); }
  }
  return keep;
}

async function vendor(pkg) {
  const meta = await (await fetch(`https://registry.npmjs.org/${pkg.name}/${pkg.version}`)).json();
  const tgz = Buffer.from(await (await fetch(meta.dist.tarball)).arrayBuffer());
  const [alg, want] = meta.dist.integrity.split('-');
  const got = createHash(alg).update(tgz).digest('base64');
  if (got !== want) throw new Error(`${pkg.name}: integrity mismatch`);
  const files = untar(gunzipSync(tgz));
  const keep = closure(files, pkg.entries);
  for (const d of pkg.dirs) for (const f of files.keys()) if (f.startsWith(d)) keep.add(f);
  for (const f of pkg.files) keep.add(f);
  const dest = join(VENDOR, pkg.name);
  rmSync(dest, { recursive: true, force: true });
  for (const f of keep) {
    const p = join(dest, f);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, files.get(f));
  }
  return { ...pkg, tarball: meta.dist.tarball, integrity: meta.dist.integrity, license: meta.license, count: keep.size };
}

const done = [];
for (const pkg of PACKAGES) done.push(await vendor(pkg));
const lines = ['Vendored libraries (generated by tools/vendor.mjs, do not edit by hand)', ''];
for (const p of done) {
  lines.push(`${p.name}@${p.version}`, `  license: ${p.license}`, `  tarball: ${p.tarball}`, `  integrity: ${p.integrity}`, `  files: ${p.count}`);
  for (const [spec, path] of Object.entries(p.importMap)) lines.push(`  import map: "${spec}" -> ./vendor/${p.name}/${path}`);
  if (!Object.keys(p.importMap).length) lines.push('  import map: none, used by tools/check.mjs only');
  lines.push('');
}
writeFileSync(join(VENDOR, 'VERSIONS.txt'), lines.join('\n'));
console.log(done.map(p => `${p.name}@${p.version} ${p.count} files`).join('\n'));
